services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: wushu-backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
